In [1]:
import pandas as pd
import numpy as np 

In [2]:
df = pd.read_csv('W:\ML_practice_dataset\sentiment_analysis\Evaluation-dataset.csv', header=None)
df.head(2)

0                        1   \
0  Tires where delivered to the garage of my choi...  garage service positive   
1  Easy Tyre Selection Process, Competitive Prici...  garage service positive   

                         2    3    4    5    6    7    8    9    10   11   12  \
0  ease of booking positive  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
1  value for money positive  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

    13   14  
0  NaN  NaN  
1  NaN  NaN

In [3]:
df.shape

(10132, 15)

In [4]:
df.isnull().sum()


0         0
1      2003
2      5893
3      8594
4      9687
5     10004
6     10096
7     10119
8     10124
9     10128
10    10131
11    10131
12    10131
13    10131
14    10131
dtype: int64

In [5]:
selected_colums=[0,1]
new_df = df[selected_colums]
new_df.head(3)

0                         1
0  Tires where delivered to the garage of my choi...   garage service positive
1  Easy Tyre Selection Process, Competitive Prici...   garage service positive
2         Very easy to use and good value for money.  value for money positive

In [6]:
new_df.isnull().sum()

0       0
1    2003
dtype: int64

In [7]:
new_df.shape

(10132, 2)

In [8]:
new_df=new_df.dropna()

In [9]:
new_df.isnull().sum()

0    0
1    0
dtype: int64

lets rename our two columns

In [10]:
new_name={0:"Review",1:"Feedback"}
new_df.rename(columns=new_name,inplace=True)
new_df.head(1)

Review                 Feedback
0  Tires where delivered to the garage of my choi...  garage service positive

Now lets look at the feedback  columns and get our positive or negative review 

In [11]:
new_df["Feedback"]

0           garage service positive
1           garage service positive
2          value for money positive
3          ease of booking positive
4                 location positive
                    ...            
10125         tyre quality positive
10126      ease of booking positive
10127               refund positive
10128    length of fitting positive
10129             location positive
Name: Feedback, Length: 8129, dtype: object

In [12]:
new_df["Sentiment"]=new_df["Feedback"].apply(lambda x:'positve'if 'positive' in x.lower() else 'negative' if 'negative' in x.lower() else 'Neutral')


In [13]:
new_df['Sentiment'].value_counts()

Sentiment
positve     6937
negative    1162
Neutral       30
Name: count, dtype: int64

In [14]:
new_df=new_df[new_df["Sentiment"]!="Neutral"]

In [15]:
new_df['Sentiment'].value_counts()

Sentiment
positve     6937
negative    1162
Name: count, dtype: int64

In [16]:
new_df.isnull().sum()

Review       0
Feedback     0
Sentiment    0
dtype: int64

In [17]:
x=new_df.drop(columns=["Sentiment","Feedback"],axis=1)

In [18]:
x.head(5)

Review
0  Tires where delivered to the garage of my choi...
1  Easy Tyre Selection Process, Competitive Prici...
2         Very easy to use and good value for money.
3              Really easy and convenient to arrange
4  It was so easy to select tyre sizes and arrang...

In [19]:
y=new_df["Sentiment"]
y.head(3)

0    positve
1    positve
2    positve
Name: Sentiment, dtype: object

In [20]:
y=y.map({'positve':1,'negative':0})
y.head(5)

0    1
1    1
2    1
3    1
4    1
Name: Sentiment, dtype: int64

In [21]:
y.value_counts()

Sentiment
1    6937
0    1162
Name: count, dtype: int64

In [22]:
y.isnull().sum()

0

Now i need to clean my review column and remove stopwords and punctuation  

In [23]:
import re

In [24]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\pande\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [25]:
text = "This is an example sentence. Tokenize it!"

In [26]:
from nltk.tokenize import word_tokenize
tokens=word_tokenize(text)
print(tokens)

['This', 'is', 'an', 'example', 'sentence', '.', 'Tokenize', 'it', '!']


In [27]:
from nltk.corpus import stopwords

In [28]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\pande\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [30]:
from nltk.corpus import stopwords
def clean_text(text):
    
    text=text.lower()
    tokens=word_tokenize(text)
    
    text=[word for word in tokens if word.isalpha()]
    


    stop_words=set(stopwords.words('english'))
    filtered_words = [word for word in text if word not in stop_words]

    text=" ".join(filtered_words)

    return text
    
    
    

In [31]:
import re

In [32]:
new_df['clean_text']=new_df['Review'].apply(clean_text)

In [33]:
new_df.head(3)

Review  \
0  Tires where delivered to the garage of my choi...   
1  Easy Tyre Selection Process, Competitive Prici...   
2         Very easy to use and good value for money.   

                   Feedback Sentiment  \
0   garage service positive   positve   
1   garage service positive   positve   
2  value for money positive   positve   

                                          clean_text  
0  tires delivered garage choice garage notified ...  
1  easy tyre selection process competitive pricin...  
2                          easy use good value money

In [34]:
new_df["Review"][20]

'No hassle, no fuss and a good price'

In [35]:
sentence='No hassle, no fuss and a good price'
print(clean_text(sentence))

hassle fuss good price


In [36]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [37]:
def stem_data(data):
    tokens=word_tokenize(data)
    tokens=[ps.stem(word) for word in tokens]
    return " ".join(tokens)
    return tokens

# To check if the function is working 
sentence = "I am loving this weather and the beautiful flowers"
print(stem_data(sentence))


new_df['clean_text']=new_df['clean_text'].apply(stem_data)


i am love thi weather and the beauti flower


In [38]:
new_df.head(5)

Review  \
0  Tires where delivered to the garage of my choi...   
1  Easy Tyre Selection Process, Competitive Prici...   
2         Very easy to use and good value for money.   
3              Really easy and convenient to arrange   
4  It was so easy to select tyre sizes and arrang...   

                   Feedback Sentiment  \
0   garage service positive   positve   
1   garage service positive   positve   
2  value for money positive   positve   
3  ease of booking positive   positve   
4         location positive   positve   

                                          clean_text  
0  tire deliv garag choic garag notifi deliv day ...  
1  easi tyre select process competit price excel ...  
2                           easi use good valu money  
3                         realli easi conveni arrang  
4  easi select tyre size arrang local fit price c...

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer


In [101]:
vectorizer=TfidfVectorizer(max_features=5000)

In [102]:
x_idf=vectorizer.fit_transform(new_df["clean_text"]).toarray()

In [42]:
print("shape of the X_idf",x_idf.shape)

shape of the X_idf (8099, 4373)


Now we need to to balance this Dataset with the help of SMOTE  

In [43]:
from imblearn.over_sampling import SMOTE

In [44]:
y.shape

(8099,)

In [45]:
y.value_counts()

Sentiment
1    6937
0    1162
Name: count, dtype: int64

In [46]:
y.values

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [49]:
smote=SMOTE(random_state=42)
X_resampled,y_resampled=smote.fit_resample(x_idf,y)

In [50]:
X_resampled.shape

(13874, 4373)

In [51]:
y_resampled.shape

(13874,)

In [52]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.33, random_state=42)

In [53]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score

In [54]:
gnb=GaussianNB()
mnb=MultinomialNB()
bnb=BernoulliNB()

In [55]:

gnb.fit(X_train,y_train)
y_pred1 = gnb.predict(X_test)
print(accuracy_score(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))
print(precision_score(y_test,y_pred1))

0.6440270801485041
[[2273    6]
 [1624  676]]
0.9912023460410557


In [56]:

mnb.fit(X_train,y_train)
y_pred2 = mnb.predict(X_test)
print(accuracy_score(y_test,y_pred2))
print(confusion_matrix(y_test,y_pred2))
print(precision_score(y_test,y_pred2))

0.9178860013103297
[[2137  142]
 [ 234 2066]]
0.9356884057971014


In [57]:
bnb.fit(X_train,y_train)
y_pred3 = bnb.predict(X_test)
print(accuracy_score(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))
print(precision_score(y_test,y_pred3))

0.8215767634854771
[[1581  698]
 [ 119 2181]]
0.7575547064953109


In [58]:

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

In [59]:
svc = SVC(kernel='sigmoid', gamma=1.0)
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth=5)
lrc = LogisticRegression(solver='liblinear', penalty='l1')
rfc = RandomForestClassifier(n_estimators=50, random_state=2)
abc = AdaBoostClassifier(n_estimators=50, random_state=2)
bc = BaggingClassifier(n_estimators=50, random_state=2)
etc = ExtraTreesClassifier(n_estimators=50, random_state=2)
gbdt = GradientBoostingClassifier(n_estimators=50,random_state=2)
xgb = XGBClassifier(n_estimators=50,random_state=2)

In [60]:
etc.fit(X_train,y_train)
y_pred3 = bnb.predict(X_test)
print(accuracy_score(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))
print(precision_score(y_test,y_pred3))

0.8215767634854771
[[1581  698]
 [ 119 2181]]
0.7575547064953109


In [61]:

clfs = {
    'SVC' : svc,
    'KN' : knc, 
    'NB': mnb, 
    'DT': dtc, 
    'LR': lrc, 
    'RF': rfc, 
    'AdaBoost': abc, 
    'BgC': bc, 
    'ETC': etc,
    'GBDT':gbdt,
    'xgb':xgb
}

In [62]:
def train_classifer(clf,X_train,y_train,X_test,y_test):
    clf.fit(X_train,y_train)
    y_pred=clf.predict(X_test)
    accuracy=accuracy_score(y_test,y_pred)
    precision=precision_score(y_test,y_pred)
    return accuracy,precision

In [63]:
train_classifer(svc,X_train,y_train,X_test,y_test)

(0.9264031447914391, 0.9403319874383131)

In [64]:
accuracy_list1=[]
precision_list1=[]

for name,clf in clfs.items():
    current_accuracy,current_precision=train_classifer(clf,X_train,y_train,X_test,y_test)
    print("For",name)
    print("Accuracy-    ",current_accuracy)
    print("Precision-  ",current_precision)

    accuracy_list1.append(current_accuracy)
    precision_list1.append(current_precision)

In [65]:
performance_df=pd.DataFrame({'Algorithm':clfs.keys(),'Accuracy':accuracy_list1,'Precision':precision_list1}).sort_values('Precision',ascending=False)

In [66]:
performance_df

In [67]:
# voting classifer
etc = ExtraTreesClassifier(n_estimators=50, random_state=2)
knc = KNeighborsClassifier()

from sklearn.ensemble import VotingClassifier


In [68]:
voting= VotingClassifier(estimators=[('et',etc),('kn',knc)],voting='soft')

In [69]:
voting.fit(X_train,y_train)

In [70]:
y_pred = voting.predict(X_test)
print("Accuracy",accuracy_score(y_test,y_pred))
print("Precision",precision_score(y_test,y_pred))


In [71]:
import pickle

In [72]:
pickle.dump(vectorizer,open('vectorizer.pkl','wb'))
pickle.dump(etc,open('model.pkl','wb'))


In [117]:
input_mail = "I've been searching for the right words to thank you for this breather. I promise i wont take your help for granted and will fulfil my promise. You have been wonderful and a blessing at all times"


input=clean_text(input_mail)
# print(input)

stem_input=stem_data(input)
# print(stem_input)





vect=vectorizer.transform([stem_input]).toarray()


result=svc.predict(vect)
# print(result)


if (result[0]==1):
  print('positive review')

else:
  print('negative review')



positive review


In [119]:
input_mail = " i hate your survices "

input=clean_text(input_mail)
# print(input)

stem_input=stem_data(input)
# print(stem_input)





vect=vectorizer.transform([stem_input]).toarray()


result=svc.predict(vect)
# print(result)


if (result[0]==1):
  print('positive review')

else:
  print('negative review')

negative review
